### ISSUE TITLE
How to load pretrained model and save new model?

### ISSUE THREAD

**Issue by LordonCN** [ruhyadi/yolo3d-lightning#55]
I want to know next step after training, how to do with **epoch_005.ckpt** ?
```
defaults:
  - model_checkpoint.yaml
  - early_stopping.yaml
  - model_summary.yaml
  - rich_progress_bar.yaml
  - _self_

model_checkpoint:
  dirpath: "weights"
  filename: "epoch_{epoch:03d}"
  monitor: "val/loss"
  mode: "min"
  save_last: True
  auto_insert_metric_name: False

early_stopping:
  monitor: "val/loss"
  patience: 100
  mode: "min"

model_summary:
  max_depth: -1
```
